# TODO: GENERATED BY LLM, need to revisit this file
# # Stage 1: Build the application using Maven
# FROM maven:3.8.5-openjdk-17 AS build
# WORKDIR /app
#
# # Copy the Maven project files
# COPY pom.xml .
#
# # Copy the source code
# COPY src ./src
#
# # Build the project and create the executable JAR
# RUN mvn clean install -DskipTests
#
#
# # Stage 2: Create the final, smaller image
# FROM eclipse-temurin:17-jre-jammy
# WORKDIR /app
#
# # Copy the JAR from the build stage
# COPY --from=build /app/target/onlineMenu-0.0.1-SNAPSHOT.jar .
#
# # Expose the port the application runs on
# EXPOSE 8080
#
# # Command to run the application
# ENTRYPOINT ["java", "-jar", "onlineMenu-0.0.1-SNAPSHOT.jar"]
